# Generated by Django 5.2.3 on 2025-08-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reserve_time",
            field=models.IntegerField(default=1),
        ),
    ]
