# Generated by Django 5.2.3 on 2025-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_reservation_reserve_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Ожидает подтверждения"),
                    ("active", "Активна"),
                    ("completed", "Завершена"),
                ],
                default="Ожидает подтверждения",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(
                choices=[
                    ("", "10:00"),
                    ("", "11:00"),
                    ("", "12:00"),
                    ("", "13:00"),
                    ("", "14:00"),
                    ("", "15:00"),
                    ("", "16:00"),
                    ("", "17:00"),
                    ("", "18:00"),
                    ("", "19:00"),
                    ("", "20:00"),
                    ("", "21:00"),
                    ("", "22:00"),
                ]
            ),
        ),
    ]
