# Generated by Django 5.2.3 on 2025-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="hall",
            field=models.CharField(
                choices=[("main", "Основной зал"), ("vip", "VIP зал")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.IntegerField(unique=True),
        ),
    ]
