# Generated by Django 5.2.3 on 2025-08-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_alter_table_hall_alter_table_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="reserve_time",
            new_name="duration",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="time",
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_time",
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
