# Generated by Django 5.2.3 on 2025-09-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Ожидает подтверждения"),
                    ("active", "Активна"),
                    ("completed", "Завершена"),
                    ("cancelled", "Отменена"),
                ],
                default="created",
                max_length=100,
            ),
        ),
    ]
