# Generated by Django 5.2.3 on 2025-09-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0009_alter_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
