# Generated by Django 5.2.3 on 2025-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_reservation_first_name_reservation_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
