# Generated by Django 5.2.3 on 2025-09-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0011_alter_content_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carousel", "Карусель"),
                    ("promotions", "Акции"),
                    ("services", "Услуги"),
                    ("team", "Команда"),
                    ("mission", "Миссия ресторана"),
                    ("history", "История ресторана"),
                    ("contacts", "Контакты"),
                    ("news", "Новости"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
