# Generated by Django 5.2.3 on 2025-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0012_content_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carousel", "Карусель"),
                    ("promotions", "Акции"),
                    ("services", "Услуги"),
                    ("team", "Команда"),
                    ("mission", "Миссия ресторана"),
                    ("history", "История ресторана"),
                    ("contacts", "Контакты"),
                    ("news", "Новости"),
                    ("description", "Описание ресторана"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/content/"),
        ),
    ]
