# Generated by Django 5.2.3 on 2025-09-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0013_alter_content_content_type_alter_content_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_phone_number", models.CharField(max_length=12, unique=True)),
                ("phone_number", models.CharField(max_length=13, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("city", models.CharField(max_length=20)),
                ("subway", models.CharField(max_length=20)),
                ("address", models.TextField()),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
