# Generated by Django 5.2.3 on 2025-09-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0014_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="phone_number",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="subway",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
