# Generated by Django 5.2.3 on 2025-09-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0015_alter_contacts_phone_number_alter_contacts_subway"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chief", models.CharField(blank=True, max_length=100, null=True)),
                ("sous_chef", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "chief_photo",
                    models.ImageField(blank=True, null=True, upload_to="img/team/"),
                ),
                (
                    "sous_chef_photo",
                    models.ImageField(blank=True, null=True, upload_to="img/team/"),
                ),
                (
                    "team_photo",
                    models.ImageField(blank=True, null=True, upload_to="img/team/"),
                ),
                ("chief_description", models.TextField(blank=True, null=True)),
                ("sous_chef_description", models.TextField(blank=True, null=True)),
                ("team_description", models.TextField(blank=True, null=True)),
                ("chief_vk", models.URLField(blank=True, null=True)),
                ("chief_tg", models.URLField(blank=True, null=True)),
                ("sous_chef_vk", models.URLField(blank=True, null=True)),
                ("sous_chef_tg", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команда",
            },
        ),
    ]
