# Generated by Django 5.2.3 on 2025-09-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0018_service_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="tg",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contacts",
            name="vk",
            field=models.URLField(blank=True, null=True),
        ),
    ]
