# Generated by Django 5.2.3 on 2025-09-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0020_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_processed", "Не обработано"),
                    ("answered", "Дан ответ"),
                    ("not_require_answer", "Не требует ответа"),
                ],
                default="not_processed",
                max_length=100,
            ),
        ),
    ]
