# Generated by Django 5.2.3 on 2025-09-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0021_feedback_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="img/team/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("vk", models.URLField(blank=True, null=True)),
                ("tg", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Шеф",
                "verbose_name_plural": "Шефы",
            },
        ),
        migrations.CreateModel(
            name="SousChef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="img/team/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("vk", models.URLField(blank=True, null=True)),
                ("tg", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Су-шеф",
                "verbose_name_plural": "Су-шефы",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Команда", "verbose_name_plural": "Команды"},
        ),
        migrations.RenameField(
            model_name="team",
            old_name="chief_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="chief_photo",
            new_name="photo",
        ),
        migrations.RemoveField(
            model_name="team",
            name="chief",
        ),
        migrations.RemoveField(
            model_name="team",
            name="chief_tg",
        ),
        migrations.RemoveField(
            model_name="team",
            name="chief_vk",
        ),
        migrations.RemoveField(
            model_name="team",
            name="sous_chef",
        ),
        migrations.RemoveField(
            model_name="team",
            name="sous_chef_description",
        ),
        migrations.RemoveField(
            model_name="team",
            name="sous_chef_photo",
        ),
        migrations.RemoveField(
            model_name="team",
            name="sous_chef_tg",
        ),
        migrations.RemoveField(
            model_name="team",
            name="sous_chef_vk",
        ),
        migrations.RemoveField(
            model_name="team",
            name="team_description",
        ),
        migrations.RemoveField(
            model_name="team",
            name="team_photo",
        ),
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carousel", "Карусель"),
                    ("services", "Услуги"),
                    ("mission", "Миссия ресторана"),
                    ("history", "История ресторана"),
                    ("contacts", "Контакты"),
                    ("description", "Описание ресторана"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
