# Generated by Django 5.2.3 on 2025-09-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0022_chief_souschef_alter_team_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["id"],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
